### ISSUE TITLE
How can I run visda18?

### ISSUE THREAD

**Issue by sehyun03** [val-iisc/s3vaada#5]
Thank you for sharing your code.

Recently I'm trying to reproduce your work on the visda18 dataset.
On the other hand, it seems that the pair-wise computation of s3vaada consumes a lot of CPU memories.
In my case on visda18, s3vaada consume more than 180G of CPU memories which is not feasible.

Can you share the evaluation protocol and running options for visda18?

**Comment by ajarihant** [comment]
Thanks for the comment.

- We removed other classes from the VisDA-18 dataset to make it similar to AADA. For your reference, we attached a zip file containing a script to download and extract VisDA-18 data which we used for training. Please run the script datasets/ to avoid any path issues.
[getvisda18.sh.zip](https://github.com/val-iisc/s3vaada/files/7541135/getvisda18.sh.zip)
- Also, make sure to turn on the lr schedular during VisDA-18 training as stated in paper.
- To run the code for VisDA, we recommend using the following command:
`python main.py --name s2r-s3vaada --source synthetic --target real
`

Hope this will help.

**Comment by rangwani-harsh** [comment]
Hi @sehyun03 if your problem is resolved can we close this issue?
